---
title: "Psych 390"
author:
  - name: Britt Anderson
    id: ba
    email: britt@uwaterloo.ca
    affiliation: 
      - name: University of Waterloo
        city: Waterloo
        province: ON
        url: brittlab.uwaterloo.ca
format:
  html:
    code-fold: true
  pdf:
    pdf-engine: pdflatex
jupyter: python3
---

# Purpose

To learn how to approach the computer as a tool for facilitating research skills.

## Skills to support

1.  Finding, collecting, commentating, and integrating relevant research literature.
2.  Sharing and tracking data, manuscripts, analyses, results, and a finished poster or manuscript
3.  In support of the above how do you find, install, and maintain software?
4.  Large data handling
5.  Writing up your research

# Course Time/Place

PSYCH 390 Thursday 14:30 — 17:30 [PHY](https://maps.app.goo.gl/zp7p9FnLQX2vpSfx6) 313

# Instructor

Britt Anderson, PhD & MD

**Office:** PAS 4039 **email:** [britt\@uwaterloo.ca](mailto:britt@uwaterloo.ca) **Office Hours:** by appointment

# Topics to be covered

## Bibliography software and Zettlekasten

## Programming language choices for experiments

## Data Storage

### Data sharing; Big Data; Data Re-use

## Data Analysis

### Statistical programming

### Data Visualization

## Research dissemination

### Writing and sharing reproducible analyses and articles

# Grades

I know you are all concerned about grades, but I am not. It sometimes feels like University is a checklist: take the right number of courses and get the right numbers on your transcripts and you will win. But that is not the case. Success in your career depends on your being able to deploy what you have learned and being able to keep on learning. These meta-skills are the ones I am most interested in helping you progress with and there are no measurement tools that we can use in this course that will allow us to predict your future occupational success. The compromise is for me to emphasize and incentivize those practices that I have learned to be most correlated with professional success: persistence, self-learning, striving for excellence. That is why I try to grade less on what you produce than how you produce it. A spectacular fail may be worth more than a safe win at this stage of your career. That is the philosophy. How do we make this work in practice?

I will give you frequent small assignments to demonstrate that you are keeping up and working on the material. I will assess your profile in class: do you come, are your interactive, are you prepared, and you collaborative; and I will provide a final project goal for you to try and stretch your wings and put in practice what you have learned.

My experience is that I don't have to be a strict grader. The world is a far harder grader than I will ever be. You can easily find a way to get a good number in my class without learning a whole lot. That will be a very short term gain. I encourage you to be ambitious for yourselves. I hope that you will be more proud of what you have learned in this course than any particular pride in how it helps your GPA.


## Details

1.  Assignments - 60%

2.  Participation - 10%

3.  Final Project - 30%

4.  Extra Credit Sona - 3%

## Sona Participation and Research Experience Marks Information and Guidelines

Experiential learning is considered an integral part of the
undergraduate program in Psychology. Research participation is one
example of this, article review is another. A number of undergraduate
courses have been expanded to include opportunities for Psychology
students to earn grades while gaining research experience.

Since experiential learning is highly valued in the Department of
Psychology, students may earn a "Bonus" grade of up to 3%** in this
course through research experience. Course work will make up 100% of the
final mark and your SONA will add up to an additional 3% to this final
grade.

The two options for earning research experience grades; participation in
research through online remotely operated and In Lab studies, as well as
article review; are described below. Students may complete any
combination of these options to earn research experience grades. Credits
will be permitted to be earned with half from online, and the other half
(1.5) from In-lab or Remote Access studies.

### Option 1: Participation in Psychology Research

Research participation is coordinated by the Research Experiences Group
(REG). Psychology students may volunteer as research participants in
remotely operated, In Lab and/or online (web-based) studies conducted by
students and faculty in the Department of Psychology. Participation
enables students to learn first-hand about psychology research and
related concepts. Many students report that participation in research is
both an educational and interesting experience. Please be assured that
all Psychology studies have been reviewed and received ethics clearance
through a University of Waterloo Research Ethics Board. 

#### How to earn extra marks for your Psychology course(s) this term by participating in studies 

-   You will earn \"credits\" which will be converted to \"marks\" (1
    credit = 1%)
-   You can schedule your studies using the \"Sona\" website.

Educational focus of participation in research

To maximize the educational benefits of participating in research,
students will receive feedback information following their participation
in each study detailing the following elements:

-   Purpose or objectives of the study
-   Dependent and independent variables
-   Expected results
-   References for at least two related research articles
-   Provisions to ensure confidentiality of data
-   Contact information of the researcher should the student have
    further questions about the study
-   Contact information for the Director of the Office of Research
    Ethics should the student wish to learn more about the general
    ethical issues surrounding research with human participants, or
    specific questions or concerns about the study in which s/he
    participated.

Participation in remotely operated (counts as the same as in-lab)
studies has increment values of 0.5 participation credits (grade
percentage points) for each 30-minutes of participation. Participation
in ONLINE studies is worth .25 credits for each 15-minutes of
participation. Researchers will record student's participation and at
the end of the term the REG Coordinator will provide the course
instructor with a credit report of the total credits earned by each
student.

**How to participate?**

Study scheduling, participation and grade assignment is managed using
the SONA online system. All students enrolled in this course have been
set up with a SONA account.  You must get started early in the term.

For instructions on how to log in to your SONA account and for a list
of important dates and deadlines please, as soon as possible, go to:

[Participating/SONA information: How to log in to Sona and sign up for
studies](https://uwaterloo.ca/research-experiences-group/welcome-research-experiences-group-and-sona/sona-information)

[Please do not ask the Course Instructor or REG Coordinator for
information unless you have first thoroughly read the information
provided on this
website.](https://uwaterloo.ca/research-experiences-group/welcome-research-experiences-group-and-sona/sona-information)

More information about the REG program in general is available at:\
[Sona Information on the REG Participants
website](https://uwaterloo.ca/research-experiences-group/welcome-research-experiences-group-and-sona/sona-information)
or you can check the [Sona FAQ on the REG website
homepage](https://uwaterloo.ca/research-experiences-group/sites/ca.research-experiences-group/files/uploads/files/sona_faq_for_fall_2019.pdf)
for additional information.

### Option 2: Article Review as an alternative to participation in research

Students are not required to participate in research, and not all
students wish to do so. As an alternative, students may opt to gain
research experience by writing short reviews (1½ to 2 pages) of research
articles relevant to the course. The course instructor will specify a
suitable source of articles for this course (i.e., scientific journals,
newspapers, magazines, other printed media). *You must contact your TA
to get approval for the article you have chosen before writing the
review.* Each review article counts as one percentage point. To receive
credit, you must follow specific guidelines. The article review must:

-   **Be submitted before the** [last day of
    lectures](http://www.quest.uwaterloo.ca/undergraduate/dates.html)**.
    Late submissions will NOT be accepted under ANY circumstances.**
-   Be typed
-   Fully identify the title, author(s), source and date of the
    article. A copy of the article must be attached.
-   Identify the psychological concepts in the article and indicate the
    pages in the textbook that are applicable. Critically evaluate the
    application or treatment of those concepts in the article. If
    inappropriate or incorrect, identify the error and its implications
    for the validity of the article. You may find, for example,
    misleading headings, faulty research procedures, alternative
    explanations that are ignored, failures to distinguish factual
    findings from opinions, faulty statements of cause-effect relations,
    errors in reasoning, etc. Provide examples whenever possible.
-   Clearly evaluate the application or treatment of those concepts in
    the article.
-   Keep a copy of your review in the unlikely event we misplace the
    original.


# Boilerplate

## Cost of Learning Materials

Students need to have access to a laptop for in course programming exercises. This does not need to be purchased for the course, but it does need to be available, and it is presumed that all students currently enrolled in advanced undergraduate studies have access to a computer. The cost is \$0.00.

The computer must run a full operating system (OSX/Windows/Linux). Phones and tablets running iOS or Android will not be sufficient.

## **Academic integrity**:

In order to maintain a culture of academic integrity, members of the University of Waterloo community are expected to promote honesty, trust, fairness, respect and responsibility. \[Check [the Office of Academic Integrity](https://uwaterloo.ca/academic-integrity/) for more information.

## **Grievance:**

A student who believes that a decision affecting some aspect of their university life has been unfair or unreasonable may have grounds for initiating a grievance. Read [Policy 70, Student Petitions and Grievances, Section 4](https://uwaterloo.ca/secretariat/node/75). When in doubt, please be certain to contact the department’s administrative assistant who will provide further assistance.

## **Discipline:**

A student is expected to know what constitutes academic integrity to avoid committing an academic offence, and to take responsibility for their actions. \[Check [the Office of Academic Integrity](https://uwaterloo.ca/academic-integrity/) for more information.\] A student who is unsure whether an action constitutes an offence, or who needs help in learning how to avoid offences (e.g., plagiarism, cheating) or about “rules” for group work/collaboration should seek guidance from the course instructor, academic advisor, or the undergraduate associate dean. For information on categories of offences and types of penalties, students should refer to [Policy 71, Student Discipline](https://uwaterloo.ca/secretariat/node/72). For typical penalties, check [Guidelines for the Assessment of Penalties](https://uwaterloo.ca/secretariat/guidelines/guidelines-assessment-penalties).

## **Appeals:**

A decision made or penalty imposed under [Policy 70, Student Petitions and Grievances](https://uwaterloo.ca/secretariat/node/75) (other than a petition) or [Policy 71, Student Discipline](https://uwaterloo.ca/secretariat/node/72) may be appealed if there is a ground. A student who believes they have a ground for an appeal should refer to [Policy 72, Student Appeals](https://uwaterloo.ca/secretariat/policies-procedures-guidelines/policy-72).

## **Note for students with disabilities:**

[AccessAbility Services](https://uwaterloo.ca/accessability-services/), located in Needles Hall, Room 1401, collaborates with all academic departments to arrange appropriate accommodations for students with disabilities without compromising the academic integrity of the curriculum. If you require academic accommodations to lessen the impact of your disability, please register with AccessAbility Services at the beginning of each academic term.