project:
  type: book
  output-dir: ../docs

book:
  title: "P390"
  author: "Britt Anderson"
  date: "Winter 2025"
  cover-image: p390cover.png
  sidebar: 
    search: true  
  chapters:
    - index.qmd
    - intro.qmd
    - cCmpResTool.qmd
    - cOpenResearch.qmd
    - cCode.qmd
    - cWriting.qmd
    - cExps.qmd
    - cBiblio.qmd
    - cServer.qmd
    - cLLM.qmd
    - cDatabase.qmd
    - summary.qmd
  appendices:
    - cGit.qmd
    - cOSX.qmd
    - python-venv.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book
    template-partials: 
      - title.tex
    
engine: knitr


