project:
  type: book
  output-dir: ../docs

book:
  title: "P390"
  author: "Britt Anderson"
  date: "Winter 2025"
  cover-image: p390cover.png
  sidebar: 
    search: true  
  chapters:
    - index.qmd
    - intro.qmd
    - cOpenFairRes.qmd
    - cBasicTooling.qmd
    - cTerminal.qmd
    - cGit.qmd
    - cWebSite.qmd  
    - cCode.qmd
    - cR.qmd
    - cPython.qmd
    - cHandlingData.qmd
    - cProgExpPosner.qmd
    - cRPandasComparison.qmd
    - cLabNotebooks.qmd
    - cLabNoteBookQuartoExample.qmd
    - cWriting.qmd
    - cBiblio.qmd
    - cLLM.qmd
    - summary.qmd
  appendices:
    - cOSX.qmd
    - cWindows.qmd
    - python-venv.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
    code-overflow: wrap
  pdf:
    documentclass: book
highlight-style: ayu 
engine: knitr


