project:
  type: book

book:
  title: "p390"
  author: "Britt Anderson"
  date: "Winter 2025"
  chapters:
    - index.qmd
    - intro.qmd
    - c2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



