

### Coding

For a lot of the above we need to know how to code. In order to write code we need minimally to answer two questions. What language? What tooling?

#### Languages

What should I consider when selecting a programming language? Will it do what I need it to do now and tomorrow.

-   Is SPSS a good language for statistics?
-   Is R a good language for statistics?
-   Is Python a good language for statistics?
-   Is R a good language for coding a web app?
-   Is R a good language for coding an in-lab visual experiment?
-   Should you use Julia? Common Lisp? Haskell? Lean? OCaml? Rust? Go?

::: {.content-hidden}
Break up class to do some quick research and make a case for each. Goal is to help them see the diversity of what is out there. One of the ideas is the Swiss Army Knife idea. It is a pretty handy to thing to have, but is it the best tool for anything?

:::

How do you *future proof*?
-   If languages go in and out of fashion what is it you should really be learning about programming? What are good coding practices? 

::: {.content-hidden} 
Another possible classroom exercise.
-   documentation
-   small functions
-   avoid spaghetti
-   use libraries

:::

### IDEs

-   Who are you writing code for? Human or Machine?
-   What is an IDE? What makes for a good IDE?

#### Using an IDE

For this course we will default to [VSCode](https://code.visualstudio.com/), because it is currently very popular and becoming somewhat of a standard. Everything said above about not getting to attached to the flavor of the month applies to IDEs. Especially since VSCode is a tool tied to Microsoft. However, there is an [opensource build](https://vscodium.com/) of VSCode that you can use instead. You can also use anyother tool you want as long as you can figure out how to make it do the things I will ask you to do. I, for one, live in [Emacs](https://www.gnu.org/software/emacs/).

#### VSCode

{{< video https://www.youtube.com/embed/B-s71n0dHUk?si=y3fy80M0mGxGLwr5
    title="Learn Visual Studio Code in 7 Minutes"
>}}

-   [Basics video](https://code.visualstudio.com/docs/introvideos/basics)
-   [Using VSCode with R](https://code.visualstudio.com/docs/languages/r)
-   [Using VSCode with Python](https://code.visualstudio.com/docs/languages/python)

*Exercise* Install VSCode

#### Jupyter Notebooks

What are jupyter notebooks? Are jupyter notebooks ide's? What are their purpose? What languages to they support?

#### Quarto

What is RStudio? What happened to RStudio? How does Quarto relate to RStudio? What languages does it support? Can you write code in it? Can you write text in it? Can you write an article in it?

### Databases and management

-   [What is it](https://www.dataversity.net/what-is-database-management/)
-   [A book on DuckDB - database stuff](https://learning-oreilly-com.proxy.lib.uwaterloo.ca/library/view/getting-started-with/9781803241005/B18270_01.xhtml#_idTextAnchor015)
-   [MariaDB](https://mariadb.org/) This SQL like, and open source. Might be easier to get started with and still be SQL enough to give them some professional benefits. I was thinking we could get some data online, often they come as CSV's and read it into the database? This is [one example](https://www.simplified.guide/mysql-mariadb/import-csv) how. A [blog](https://kinsta.com/blog/mariadb-vs-postgresql/) that compares MariaDB to SQL. A [quickie tutorial](https://mariadb.com/kb/en/mariadb-basics/).
-   Why would I want to use a relational database over a csv file (or R data frame or similar)? This could be a class exercise and discussion.
-   *Exercise* Download MariaDB

### Sharing The Results

### Reproducible Report Authoring


### Miscellaneous Readings and Topics

### Datascience

-   [one person's roadmap for non-cs grads](https://medium.com/@fareedkhandev/complete-roadmap-of-data-science-for-non-cs-cs-students-equivalent-to-a-degree-1a0a810360c0)

### Grant Funding

At the moment I am not sure if will have time for this. But thinking of having the students review the peer review manual for NSERC Discovery Grants. Then have them each write a minimal proposal. Assign the proposals to members of the class, and then hold our own reviewers meeting to decide which projects to fund. Top grants get performed for experiments? Get extra-credit points?