# Windows Specific Advice

## General

   Go slow.

   Read, pause, reflect, and then, and only then, type and hit enter.

## Context

   Windows is a very locked down system. Developing applications for windows using only windows tools can be limiting. You don't know what you will want to do in the future. By using a linux style system with linux inflected tools you will be learning general methods that will broaden what you can do in the future, but living in two worlds can be tricky and you will need to keep straight when you are in windows proper and when you are in the subsystem for linux. 

## Windows Subsystem for Linux
  This is a relatively new feature for the Windows operating system that lets you install a linux virtual machine inside your current Windows distribution. You can thus "use" linux while still running windows. You can use it just for terminal commands or you can run some visual applications as well. 

### Make sure you are on Windows 10 or 11 and that you are updated.

There will be two steps to this process. First you will install windows subsystem for linux, usually just called WSL. This will be easier if you have the [windows power shell](https://learn.microsoft.com/en-us/powershell/scripting/install/install-powershell-on-windows?view=powershell-7.5) available.  

Once you have installed WSL you will then install a linux distribution. Since ubuntu is one of the most common and best documented of the linux distributions that is the distribution I suggest you start with.
You will use power shell to get wsl and ubuntu installed. After having done that you will primarily use the linux terminal that you have installed. This can be launched via you applications. Just look for Ubuntu. 
    
### Then follow the instructions per [microsoft](https://learn.microsoft.com/en-us/windows/wsl/install).

## VSCode

   This is an integrated development environment for numeous coding languages including the three file types that we will focus on: .qmd, .py, and .r files. 
   
   Downloading it and having it play nice with your linux environment requires special care. Make sure you follow instructions specifically related to wsl. Usually you will install the Windows VS Code application, but when you go to "launch" it for files that will be stored in your linux land you will use your *linux* terminal with the command `code .`. Don't forget the period. That should start it from your home directory in linux land. 

   [Install](https://code.visualstudio.com/download)

## Git

If you are using WSL then you probably already have it. Enter you WSL terminal and try `git --version`. If you see an answer you have it. If you don't want to use WSL you can [install](https://git-scm.com/install/windows) it for Windows directly. 

## Python

First, get [uv](https://docs.astral.sh/uv/getting-started/installation/).

Optional, [install a version of python](https://docs.astral.sh/uv/guides/install-python/). It may be better *not* to do this. You can get the particular version of python you need at the time you create your virtual environment in step two below. 

Second, [practice setting up a virtual environment](https://docs.astral.sh/uv/guides/install-python/).

If you are in your linux terminal you will use terminal commands such `cd` to navigate to a particular directory and then I recommend making a test directory until you are confident in what you are doing. For example, `cd ~` takes you to your home directory; `mkdir test` creates a directory called "test"; `cd ./test` moves you into your test directory, and finally, `uv venv -p 3.10` will install a virtual environment in the "test" directory (called `.venv` -- you would have to `ls -a` to see that). You will then activate this environment with `source .venv/bin/activate` to make it live, and `deactivate` when you are done. 

Third, [install some packages](https://docs.astral.sh/uv/pip/packages/). *After* having created the virtual environment and activated it. 

