# Preface {.unnumbered}

This course is an effort to expose research minded undergraduate students in psychology to the wealth of computational and programming tools that they can use to ease their research tasks, and in some cases do things that they could not do otherwise. It is in written as a series of `qmd` files. This makes it a [Quarto](https://quarto.org/) book. Quarto can be seen as a successor to RStudio and Rmd files. It is in another in the series of markup languages that allow you to write in plain text, but by following certain conventions, make it easy to convert those plain text files into any number of output formats such as html (for a website) or pdf (for a book or article). I want to emphasize the writing of reproducible code and papers. There are many different systems that can accomplish this goal. Quarto is just one option, but it is one of the easier ones to get started with. In addition, to Quarto, we will explore IDEs via Visual Studio Code, and also some of the basics of programming, bibliographic tools, and auxilliary tools like zettlekasten and databases. 

You do not need to read this book in order. At this early draft stage some things are repeated, some are missing, and some are misordered. You may have to jump around to find what you are looking for. 

One of the key lessons for learning to use your computer effectively as a research tool is learning how to do things *generally*; rather than mastering one particular variety of software; we want to be able to figure out how to use whatever is the right tool for a particular application. Your needs will change as your science evolves. The tools available will change. You don't want to be still using the software you learned in University twenty years from now. If you are you will be less able to tackle the problems that interest you. Instead of doing the key experiment, you will be figuring out how to do the experiment that is most like, but not quite, the right one, but is as well as you can do with the old software you know how to use. 

